In [1]:
#question1

In [2]:
import numpy as np
n_array=np.array([[2,10],[3,8]])
m=n_array.tolist()
print(m)

[[2, 10], [3, 8]]


In [3]:
import numpy as np
n_array=np.array([[2,10],[3,8]])
m=n_array.trace()
print(m)

10


In [4]:
import numpy as np
array=np.eye(5)
print(array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [5]:
m=array.trace()
print(m)

5.0


In [6]:
import numpy as np
array=np.random.randint(2, 10, size=(2,3))
print("Original array: ")
print(array)
print("Values bigger than 2 =",array[array>2])

Original array: 
[[7 4 9]
 [9 6 5]]
Values bigger than 2 = [7 4 9 9 6 5]


In [7]:
#question4

In [11]:
import numpy as np
A=np.random.randint(8, 10, size=(3,3))
B=np.random.randint(6, 40, size=(3,3))

In [13]:
C=np.add(A,B)
print(C)

[[19 26 27]
 [27 24 16]
 [45 43 29]]


In [14]:
#question5

In [18]:
X=np.array([[1,2],
            [3,4]])
Y= X - X.mean(axis=1, keepdims=True)
print(Y)

[[-0.5  0.5]
 [-0.5  0.5]]
